model:
  asr:
    C:\Users\mifan\workspaces\Models\Qwen3-ASR-1.7B
  aligner:
    C:\Users\mifan\workspaces\Models\Qwen3-ForcedAligner

ffmpeg:
  exe:
    C:\ffmpeg-8.1.2-full_build\bin\ffmpeg.exe

device:
  auto

subtitle:
  format:
    srt

chunk:
  seconds:
    300